import { StyleSheet } from "react-native";
import { FIELD_ROW_GAP } from "@/src/lib/entryFlow/newEntryUtils";
import { colors } from "@/src/lib/theme";
import { fonts } from "@/src/lib/typography";

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.screenBg },
  content: { paddingHorizontal: 18, paddingTop: 16, paddingBottom: 28, gap: 14 },
  navRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    paddingBottom: 16,
  },
  navBrand: { color: colors.textPrimary, fontSize: 22, fontWeight: "700" },
  backButton: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  backButtonText: { color: colors.textPrimary, fontSize: 12, fontWeight: "700" },
  pageHeader: { marginTop: 4, gap: 6 },
  eyebrow: {
    color: colors.accentSecondary,
    fontSize: 9,
    fontWeight: "700",
    letterSpacing: 3,
    textTransform: "uppercase",
  },
  title: { color: colors.textPrimary, fontFamily: fonts.serif.light, fontSize: 28, lineHeight: 34 },
  subtitle: { color: colors.textSecondary, fontSize: 14, lineHeight: 20 },
  card: {
    borderRadius: 24,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surfaceTinted,
    padding: 16,
    gap: 12,
  },
  uploadBox: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.border,
    padding: 12,
    gap: 8,
  },
  uploadTextWrap: { gap: 4 },
  uploadHint: { color: colors.accentPrimary },
  uploadGalleryFrame: {
    width: "100%",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.surfaceHover,
    backgroundColor: colors.surfaceHover,
    overflow: "hidden",
  },
  uploadPhotoSlide: {
    position: "relative",
  },
  uploadPreview: {
    width: "100%",
    height: 232,
    backgroundColor: colors.surfaceHover,
  },
  uploadPreviewTypeOverlay: {
    position: "absolute",
    left: 10,
    top: 10,
    width: 128,
  },
  uploadPhotoDotRow: {
    position: "absolute",
    bottom: 10,
    left: 0,
    right: 0,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 14,
  },
  uploadPhotoDot: {
    width: 7,
    height: 7,
    borderRadius: 999,
    backgroundColor: colors.surfaceHover,
  },
  uploadPhotoDotActive: {
    width: 8,
    height: 8,
    backgroundColor: colors.accentPrimary,
  },
  uploadGalleryFooter: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    minHeight: 24,
  },
  uploadGalleryFooterActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  uploadCropButton: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.accentSoft,
    backgroundColor: colors.accentSoft,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  uploadCropButtonText: {
    color: colors.accentSecondary,
    fontSize: 11,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  uploadRemoveButton: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.borderStrong,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  uploadRemoveButtonText: {
    color: colors.textPrimary,
    fontSize: 11,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  uploadWaitingText: {
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 16,
  },
  uploadLoadingRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  uploadLoadingText: {
    color: colors.accentPrimary,
    fontSize: 12,
    lineHeight: 16,
    flex: 1,
  },
  uploadStatusText: {
    fontSize: 12,
    lineHeight: 16,
  },
  uploadStatusTextSuccess: {
    color: colors.success,
  },
  uploadStatusTextError: {
    color: colors.error,
  },
  retryActionButton: {
    alignSelf: "flex-start",
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.borderStrong,
    backgroundColor: colors.accentSoft,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  retryActionButtonText: {
    color: colors.accentSecondary,
    fontSize: 11,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  bulkLineupCard: {
    marginTop: 8,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.accentSoft,
    backgroundColor: colors.accentSoft,
    padding: 10,
    gap: 8,
  },
  bulkLineupHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  bulkLineupTitle: {
    color: colors.accentSecondary,
    fontSize: 13,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.7,
  },
  bulkBackButton: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.surfaceHover,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  bulkBackButtonText: {
    color: colors.textSecondary,
    fontSize: 11,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  bulkLineupList: {
    gap: 7,
  },
  bulkLineupRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.surfaceHover,
    backgroundColor: colors.surfaceTinted,
    paddingHorizontal: 9,
    paddingVertical: 8,
  },
  bulkLineupRowMain: {
    flex: 1,
    minWidth: 0,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  bulkLineupRowActive: {
    borderColor: colors.accentRose,
    backgroundColor: colors.accentSoft,
  },
  bulkLineupCheckbox: {
    width: 18,
    height: 18,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.borderStrong,
    alignItems: "center",
    justifyContent: "center",
  },
  bulkLineupCheckboxActive: {
    borderColor: colors.accentPrimary,
    backgroundColor: colors.accentPrimary,
  },
  bulkLineupCheckboxMark: {
    color: colors.screenBg,
    fontSize: 11,
    fontWeight: "800",
    lineHeight: 12,
  },
  bulkLineupCopy: {
    flex: 1,
    minWidth: 0,
    gap: 1,
  },
  bulkLineupWineTitle: {
    color: colors.textPrimary,
    fontSize: 12,
    fontWeight: "700",
  },
  bulkLineupWineMeta: {
    color: colors.textSecondary,
    fontSize: 11,
  },
  bulkLineupConfidence: {
    color: colors.accentSecondary,
    fontSize: 11,
    fontWeight: "700",
  },
  bulkLineupCropButton: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  bulkLineupCropButtonText: {
    color: colors.textPrimary,
    fontSize: 11,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.3,
  },
  bulkLineupMessage: {
    color: colors.accentSecondary,
    fontSize: 12,
    lineHeight: 16,
  },
  bulkGroupCard: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.surfaceHover,
    backgroundColor: colors.surfaceTinted,
    padding: 10,
    gap: 10,
  },
  bulkGroupHeader: {
    gap: 4,
  },
  bulkGroupHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  bulkGroupTitle: {
    color: colors.textPrimary,
    fontSize: 13,
    fontWeight: "700",
  },
  bulkInfoButton: {
    width: 24,
    height: 24,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.borderStrong,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.surfaceTinted,
  },
  bulkInfoButtonText: {
    color: colors.textPrimary,
    fontSize: 12,
    fontWeight: "700",
  },
  bulkGroupDescription: {
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 17,
  },
  bulkGroupHint: {
    color: colors.textSecondary,
    fontSize: 11,
    lineHeight: 16,
  },
  bulkGroupModeWrap: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flexWrap: "wrap",
  },
  bulkGroupModeButton: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surfaceHover,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  bulkGroupModeButtonActive: {
    borderColor: colors.accentHover,
    backgroundColor: colors.accentPrimary,
  },
  bulkGroupModeButtonText: {
    color: colors.textPrimary,
    fontSize: 12,
    fontWeight: "700",
  },
  bulkGroupModeButtonTextActive: {
    color: colors.screenBg,
  },
  bulkGroupFieldLabel: {
    color: colors.textPrimary,
    fontSize: 12,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.6,
  },
  bulkGroupFieldHint: {
    color: colors.textSecondary,
    fontSize: 11,
    lineHeight: 15,
  },
  bulkGroupInputError: {
    borderColor: colors.error,
  },
  bulkGroupHintText: {
    color: colors.textSecondary,
    fontSize: 11,
    lineHeight: 15,
    marginTop: 4,
  },
  eventTypeGrid: {
    flexDirection: "row" as const,
    flexWrap: "wrap" as const,
    gap: 8,
    marginTop: 6,
  },
  eventTypePill: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surfaceHover,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  eventTypePillActive: {
    borderColor: colors.accentHover,
    backgroundColor: colors.accentPrimary,
  },
  eventTypePillText: {
    color: colors.textPrimary,
    fontSize: 12,
    fontWeight: "600" as const,
  },
  eventTypePillTextActive: {
    color: colors.screenBg,
  },
  bulkGroupErrorText: {
    color: colors.accentSecondary,
    fontSize: 11,
    lineHeight: 15,
  },
  bulkRetryButton: {
    alignSelf: "flex-start",
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.borderStrong,
    backgroundColor: colors.accentRose,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  bulkRetryButtonText: {
    color: colors.accentSecondary,
    fontSize: 11,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  bulkCreateButton: {
    borderRadius: 999,
    backgroundColor: colors.accentPrimary,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 10,
    minHeight: 40,
  },
  bulkCreateButtonText: {
    color: colors.screenBg,
    fontSize: 13,
    fontWeight: "700",
  },
  bulkCancelButton: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 10,
    minHeight: 40,
  },
  bulkCancelButtonText: {
    color: colors.textPrimary,
    fontSize: 12,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  ghostButton: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.borderStrong,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  uploadActionButton: {
    alignSelf: "flex-start",
    marginTop: 2,
  },
  manualEntryButton: {
    alignSelf: "flex-start",
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.borderStrong,
    backgroundColor: colors.surfacePrimary,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  manualEntryButtonText: {
    color: colors.textPrimary,
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 0.4,
  },
  ghostButtonText: {
    color: colors.textPrimary,
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 0.6,
    textTransform: "uppercase",
  },
  drinkingNowCard: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surfaceTinted,
    paddingHorizontal: 12,
    paddingVertical: 11,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  drinkingNowCopy: {
    flex: 1,
    gap: 3,
  },
  drinkingNowTitle: {
    color: colors.info,
    fontSize: 13,
    fontWeight: "700",
  },
  drinkingNowDescription: {
    color: colors.info,
    fontSize: 12,
    lineHeight: 17,
  },
  adaptiveRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: FIELD_ROW_GAP,
  },
  adaptiveCol: {
    minWidth: 0,
  },
  adaptiveColFull: {
    width: "100%",
  },
  locationDateStack: {
    gap: 10,
  },
  twoColGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  twoColItem: {
    width: "48%",
    minWidth: 140,
  },
  twoColItemFull: {
    width: "100%",
  },
  primaryGrapeHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  primaryGrapeChipWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    alignItems: "center",
  },
  primaryGrapeChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.accentRose,
    backgroundColor: colors.accentSoft,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  primaryGrapeChipText: {
    color: colors.accentSecondary,
    fontSize: 12,
    fontWeight: "700",
  },
  primaryGrapeChipRemove: {
    color: colors.accentPrimary,
    fontSize: 12,
    fontWeight: "700",
  },
  accordion: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.surfaceHover,
    backgroundColor: colors.surfaceTinted,
    overflow: "visible",
  },
  accordionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    paddingHorizontal: 12,
    paddingVertical: 11,
  },
  accordionTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  accordionChevron: {
    color: colors.textPrimary,
    fontSize: 12,
    fontWeight: "700",
    width: 14,
    textAlign: "center",
  },
  accordionTitle: { color: colors.textPrimary, fontSize: 14, fontWeight: "600" },
  accordionBody: {
    borderTopWidth: 1,
    borderTopColor: colors.surfaceTinted,
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 8,
  },
  accordionFields: { gap: 10 },
  block: { gap: 6 },
  selectCompactBlock: { gap: 0 },
  labelRow: { flexDirection: "row", alignItems: "center", gap: 4 },
  label: { color: colors.textTertiary, fontSize: 9, fontWeight: "700", letterSpacing: 2, textTransform: "uppercase" },
  requiredStar: { color: colors.error, fontSize: 14, fontWeight: "700" },
  input: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.borderStrong,
    backgroundColor: "rgba(245,237,214,0.04)",
    color: colors.textPrimary,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 14,
  },
  inputMultiline: { minHeight: 108, textAlignVertical: "top" },
  selectTrigger: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.inputBg,
    minHeight: 42,
    paddingHorizontal: 12,
    paddingVertical: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  selectTriggerCompact: {
    minHeight: 28,
    paddingHorizontal: 8,
    paddingVertical: 5,
    borderRadius: 999,
    backgroundColor: colors.surfaceHover,
    borderColor: colors.border,
    gap: 6,
  },
  selectTriggerAccent: {
    borderColor: colors.accentRose,
    backgroundColor: colors.accentSoft,
  },
  selectTriggerCompactAmber: {
    borderColor: colors.accentRose,
    backgroundColor: colors.accentRose,
  },
  selectTriggerText: { color: colors.textPrimary, fontSize: 14, flex: 1 },
  selectTriggerTextCompact: {
    fontSize: 10,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  selectTriggerTextAccent: {
    color: colors.accentSecondary,
    fontWeight: "600",
  },
  selectChevron: { color: colors.textSecondary, fontSize: 12, fontWeight: "700" },
  selectChevronCompact: { fontSize: 9 },
  selectChevronAccent: {
    color: colors.accentPrimary,
  },
  selectPopoverCard: {
    position: "absolute",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.borderStrong,
    backgroundColor: colors.surfaceRaised,
    padding: 0,
    gap: 0,
    overflow: "hidden",
    shadowColor: colors.textPrimary,
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.15,
    shadowRadius: 18,
    elevation: 20,
  },
  selectPopoverCardAccent: {
    borderColor: colors.accentRose,
    backgroundColor: colors.surfaceRaised,
  },
  selectModalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  selectModalTitle: {
    color: colors.textPrimary,
    fontSize: 15,
    fontWeight: "700",
  },
  selectModalTitleAccent: {
    color: colors.accentSecondary,
  },
  selectModalCloseText: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: "700",
  },
  selectPopoverList: {
    width: "100%",
  },
  selectOption: {
    width: "100%",
    paddingHorizontal: 14,
    paddingVertical: 11,
  },
  selectOptionSelected: {
    backgroundColor: colors.accentRose,
  },
  selectOptionSelectedAmber: {
    backgroundColor: colors.accentRose,
  },
  selectOptionText: {
    color: colors.textSecondary,
    fontSize: 13,
    fontWeight: "600",
  },
  selectOptionTextSelected: {
    color: colors.accentSecondary,
  },
  selectOptionTextSelectedAmber: {
    color: colors.accentPrimary,
  },
  locationInputWrap: {
    position: "relative",
  },
  suggestionOverlay: {
    position: "absolute",
    left: 0,
    right: 0,
    top: 46,
    zIndex: 50,
    elevation: 12,
  },
  suggestionList: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surfaceRaised,
    overflow: "hidden",
  },
  suggestionItem: {
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  suggestionText: {
    color: colors.textSecondary,
    fontSize: 13,
  },
  inlineSuggestionList: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surfaceRaised,
    overflow: "hidden",
    marginTop: 2,
  },
  chipWrap: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  chip: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surfaceTinted,
    paddingHorizontal: 11,
    paddingVertical: 7,
  },
  chipActive: {
    borderColor: colors.accentPrimary,
    backgroundColor: colors.accentRose,
  },
  chipText: { color: colors.textSecondary, fontSize: 12, fontWeight: "600" },
  chipTextActive: { color: colors.accentSecondary },
  friendChip: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.borderStrong,
    paddingHorizontal: 10,
    paddingVertical: 7,
    backgroundColor: colors.surfaceTinted,
  },
  friendChipActive: {
    borderColor: colors.accentPrimary,
    backgroundColor: colors.accentRose,
  },
  friendText: { color: colors.textSecondary, fontSize: 12, fontWeight: "600" },
  friendTextActive: { color: colors.accentSecondary },
  popoverRoot: {
    flex: 1,
    backgroundColor: colors.surfaceTinted,
  },
  modalDismissLayer: {
    ...StyleSheet.absoluteFillObject,
  },
  visibilityGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  visibilityColumn: {
    flex: 1,
    minWidth: 210,
    gap: 8,
  },
  visibilityHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  visibilityTitle: {
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: "700",
  },
  visibilityBadge: {
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 11,
    paddingVertical: 6,
  },
  visibilityBadgeText: {
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 1,
  },
  calendarPopoverWrap: {
    position: "absolute",
  },
  popoverArrow: {
    position: "absolute",
    width: 18,
    height: 18,
    backgroundColor: colors.surfaceRaised,
    transform: [{ rotate: "45deg" }],
    borderColor: colors.borderStrong,
    borderWidth: 1,
  },
  popoverArrowTop: {
    top: -9,
  },
  popoverArrowBottom: {
    bottom: -9,
  },
  calendarCard: {
    width: "100%",
    aspectRatio: 1,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.borderStrong,
    backgroundColor: colors.surfaceRaised,
    paddingHorizontal: 10,
    paddingVertical: 10,
    gap: 6,
  },
  calendarHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  calendarNavButton: {
    width: 26,
    height: 26,
    borderRadius: 999,
    borderWidth: 0,
    alignItems: "center",
    justifyContent: "center",
  },
  calendarNavButtonText: {
    color: colors.info,
    fontSize: 18,
    fontWeight: "700",
  },
  calendarTitle: {
    color: colors.textPrimary,
    fontSize: 13,
    fontWeight: "700",
  },
  weekdayRow: {
    flexDirection: "row",
  },
  weekdayText: {
    width: "14.2857143%",
    textAlign: "center",
    color: colors.textSecondary,
    fontSize: 9,
    fontWeight: "700",
  },
  calendarGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "flex-start",
  },
  calendarSlot: {
    width: "14.2857143%",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 1,
  },
  calendarCell: {
    width: 28,
    height: 28,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
  },
  calendarCellSelected: {
    backgroundColor: colors.info,
  },
  calendarCellText: {
    color: colors.textPrimary,
    fontSize: 12,
    fontWeight: "500",
  },
  calendarCellTextSelected: {
    color: colors.screenBg,
  },
  calendarActions: {
    marginTop: 6,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  calendarResetButton: {
    minWidth: 98,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surfaceRaised,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 10,
    paddingHorizontal: 14,
  },
  calendarResetButtonText: {
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: "700",
  },
  calendarConfirmButton: {
    width: 64,
    height: 64,
    borderRadius: 999,
    backgroundColor: colors.info,
    alignItems: "center",
    justifyContent: "center",
  },
  calendarConfirmButtonText: {
    color: colors.success,
    fontSize: 30,
    fontWeight: "700",
    lineHeight: 34,
  },
  hint: { color: colors.textSecondary, fontSize: 12, lineHeight: 16 },
  error: { color: colors.accentSecondary, fontSize: 13 },
  surveyModalRoot: {
    flex: 1,
    padding: 12,
    justifyContent: "center",
    backgroundColor: colors.overlay,
  },
  surveyCard: {
    width: "100%",
    maxWidth: 620,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.surfaceHover,
    backgroundColor: colors.surfaceRaised,
    padding: 16,
    gap: 12,
    maxHeight: "90%",
  },
  surveyCardComparison: {
    maxHeight: "94%",
  },
  surveyHeader: {
    gap: 6,
  },
  surveyTitle: {
    color: colors.textPrimary,
    fontSize: 24,
    fontWeight: "700",
  },
  surveyCompareSection: {
    gap: 8,
    marginTop: 4,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: colors.surfaceHover,
  },
  surveyCompareHeader: {
    gap: 10,
  },
  surveyCompareTitleHeading: {
    color: colors.textPrimary,
    fontSize: 22,
    fontWeight: "700",
  },
  surveySkipButton: {
    alignSelf: "flex-start",
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.borderStrong,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  surveySkipText: {
    color: colors.textPrimary,
    fontSize: 11,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.6,
  },
  surveyCompareRow: {
    flexDirection: "column",
    gap: 10,
  },
  surveyCompareCard: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.border,
    overflow: "hidden",
  },
  surveyCompareImageWrap: {
    height: 176,
    backgroundColor: colors.surfaceHover,
  },
  surveyCompareImage: {
    width: "100%",
    height: "100%",
  },
  surveyCompareImageFallback: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  surveyCompareBody: {
    gap: 2,
    paddingHorizontal: 8,
    paddingVertical: 8,
    borderTopWidth: 1,
    borderTopColor: colors.surfaceHover,
  },
  surveyCompareTag: {
    color: colors.textSecondary,
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 0.7,
    textTransform: "uppercase",
  },
  surveyCompareTitle: {
    color: colors.textPrimary,
    fontSize: 12,
    fontWeight: "700",
  },
  surveyCompareMeta: {
    color: colors.textSecondary,
    fontSize: 11,
  },
  surveySubmitButton: {
    borderRadius: 12,
    backgroundColor: colors.accentPrimary,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
    minHeight: 46,
    marginTop: 2,
  },
  cropModalBackdrop: {
    flex: 1,
    backgroundColor: colors.overlay,
    justifyContent: "center",
    paddingHorizontal: 14,
  },
  cropModalCard: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.surfaceHover,
    backgroundColor: colors.surfaceRaised,
    padding: 14,
    gap: 12,
  },
  bulkInfoModalCard: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.surfaceHover,
    backgroundColor: colors.surfaceRaised,
    padding: 16,
    gap: 14,
  },
  cropModalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  cropModalTitle: {
    color: colors.textPrimary,
    fontSize: 18,
    fontWeight: "700",
  },
  cropModalCloseText: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  cropFrame: {
    width: "100%",
    aspectRatio: 1,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.surfaceHover,
    backgroundColor: colors.surfaceHover,
    overflow: "hidden",
    position: "relative",
  },
  cropFrameImage: {
    position: "absolute",
  },
  cropFrameOutline: {
    ...StyleSheet.absoluteFillObject,
    borderWidth: 2,
    borderColor: colors.accentPrimary,
  },
  cropFrameCrosshair: {
    position: "absolute",
    width: 18,
    height: 18,
    left: "50%",
    top: "50%",
    marginLeft: -9,
    marginTop: -9,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.accentPrimary,
    backgroundColor: colors.accentRose,
  },
  cropFrameLoading: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingHorizontal: 16,
  },
  cropFrameHint: {
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 16,
  },
  cropActionRow: {
    flexDirection: "row",
    gap: 10,
  },
  actionRow: { flexDirection: "row", gap: 10 },
  submitButton: {
    flex: 1,
    borderRadius: 11,
    backgroundColor: colors.accentPrimary,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
    minHeight: 46,
  },
  submitButtonDisabled: {
    opacity: 0.55,
  },
  submitButtonText: { color: colors.screenBg, fontSize: 14, fontWeight: "700" },
  cancelButton: {
    flex: 1,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.surfaceHover,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
  },
  cancelButtonText: { color: colors.textPrimary, fontSize: 14, fontWeight: "600" },
});
