import type { SensoryAxis } from "./types";

export type DescriptorMapping = {
  axis: SensoryAxis;
  value: number;
  confidence: number;
};

// Phrase-level lexicon for free-text tasting notes.
// Multi-word phrases should be normalized to lowercase, space-separated tokens.
export const DESCRIPTOR_LEXICON: Record<string, DescriptorMapping[]> = {
  // Body / texture
  "full bodied": [{ axis: "body", value: 5, confidence: 0.95 }],
  "medium bodied": [{ axis: "body", value: 3, confidence: 0.9 }],
  "light bodied": [{ axis: "body", value: 1.5, confidence: 0.95 }],
  "full body": [{ axis: "body", value: 5, confidence: 0.9 }],
  "medium body": [{ axis: "body", value: 3, confidence: 0.85 }],
  "light body": [{ axis: "body", value: 1.5, confidence: 0.9 }],
  "mouth filling": [{ axis: "body", value: 4.5, confidence: 0.7 }],
  "weighty": [{ axis: "body", value: 4.5, confidence: 0.65 }],
  "broad shouldered": [{ axis: "body", value: 4.5, confidence: 0.7 }],
  "plush": [{ axis: "body", value: 4, confidence: 0.5 }],
  "supple": [{ axis: "body", value: 2.5, confidence: 0.45 }],
  "lean": [{ axis: "body", value: 1.8, confidence: 0.55 }],
  "lithe": [{ axis: "body", value: 2, confidence: 0.45 }],
  "delicate": [{ axis: "body", value: 2, confidence: 0.4 }],
  "creamy": [{ axis: "body", value: 3.5, confidence: 0.55 }],
  "extracted": [{ axis: "body", value: 4.5, confidence: 0.6 }],
  "rich": [
    { axis: "body", value: 4.2, confidence: 0.55 },
    { axis: "concentration", value: 4, confidence: 0.5 },
  ],
  "dense": [
    { axis: "body", value: 4.5, confidence: 0.7 },
    { axis: "concentration", value: 4.5, confidence: 0.75 },
  ],
  "powerful": [
    { axis: "body", value: 4.5, confidence: 0.65 },
    { axis: "concentration", value: 4.5, confidence: 0.65 },
  ],
  "elegant": [
    { axis: "body", value: 2.5, confidence: 0.45 },
    { axis: "complexity", value: 4, confidence: 0.5 },
  ],
  "refined": [{ axis: "complexity", value: 4, confidence: 0.5 }],
  "polished": [{ axis: "complexity", value: 4, confidence: 0.5 }],
  "graceful": [{ axis: "complexity", value: 4, confidence: 0.45 }],
  "seamless": [{ axis: "complexity", value: 4, confidence: 0.45 }],

  // Acidity / freshness
  crisp: [
    { axis: "acidity", value: 4.2, confidence: 0.85 },
    { axis: "freshness", value: 4.2, confidence: 0.65 },
  ],
  bright: [
    { axis: "acidity", value: 4, confidence: 0.75 },
    { axis: "freshness", value: 4, confidence: 0.55 },
  ],
  vibrant: [
    { axis: "acidity", value: 4.3, confidence: 0.75 },
    { axis: "freshness", value: 4.3, confidence: 0.7 },
  ],
  lively: [
    { axis: "acidity", value: 3.8, confidence: 0.55 },
    { axis: "freshness", value: 4, confidence: 0.6 },
  ],
  zippy: [
    { axis: "acidity", value: 4.2, confidence: 0.75 },
    { axis: "freshness", value: 4.5, confidence: 0.65 },
  ],
  brisk: [
    { axis: "acidity", value: 4, confidence: 0.7 },
    { axis: "freshness", value: 4, confidence: 0.6 },
  ],
  bracing: [
    { axis: "acidity", value: 4.6, confidence: 0.75 },
    { axis: "freshness", value: 4.3, confidence: 0.55 },
  ],
  piercing: [{ axis: "acidity", value: 4.7, confidence: 0.65 }],
  tart: [{ axis: "acidity", value: 4.5, confidence: 0.8 }],
  tangy: [{ axis: "acidity", value: 4, confidence: 0.65 }],
  electric: [
    { axis: "acidity", value: 4.5, confidence: 0.65 },
    { axis: "freshness", value: 4.5, confidence: 0.6 },
  ],
  refreshing: [
    { axis: "acidity", value: 3.5, confidence: 0.5 },
    { axis: "freshness", value: 4.2, confidence: 0.65 },
  ],
  fresh: [{ axis: "freshness", value: 4, confidence: 0.55 }],
  mouthwatering: [{ axis: "freshness", value: 4.5, confidence: 0.65 }],
  "high acid": [{ axis: "acidity", value: 5, confidence: 0.95 }],
  "low acid": [{ axis: "acidity", value: 1.5, confidence: 0.95 }],
  flat: [{ axis: "acidity", value: 1.5, confidence: 0.75 }],
  flabby: [{ axis: "acidity", value: 1, confidence: 0.85 }],

  // Tannin / grip
  tannic: [{ axis: "tannin", value: 4.6, confidence: 0.95 }],
  "soft tannins": [{ axis: "tannin", value: 2, confidence: 0.9 }],
  "firm tannins": [{ axis: "tannin", value: 4, confidence: 0.9 }],
  "fine grained": [{ axis: "tannin", value: 3, confidence: 0.7 }],
  "dusty tannins": [{ axis: "tannin", value: 3.5, confidence: 0.75 }],
  grippy: [
    { axis: "tannin", value: 4.5, confidence: 0.85 },
    { axis: "bitterness_phenolic_grip", value: 4.25, confidence: 0.7 },
  ],
  grainy: [{ axis: "tannin", value: 3.8, confidence: 0.65 }],
  powdery: [{ axis: "tannin", value: 2.8, confidence: 0.55 }],
  smooth: [{ axis: "tannin", value: 2.2, confidence: 0.5 }],
  silky: [{ axis: "tannin", value: 2, confidence: 0.7 }],
  velvety: [{ axis: "tannin", value: 2.4, confidence: 0.7 }],
  chewy: [{ axis: "tannin", value: 4, confidence: 0.7 }],
  astringent: [
    { axis: "tannin", value: 5, confidence: 0.9 },
    { axis: "bitterness_phenolic_grip", value: 4.5, confidence: 0.8 },
  ],
  drying: [{ axis: "bitterness_phenolic_grip", value: 4, confidence: 0.65 }],
  integrated: [{ axis: "tannin", value: 3, confidence: 0.4 }],
  resolved: [{ axis: "tannin", value: 2.5, confidence: 0.35 }],
  structured: [{ axis: "tannin", value: 3.5, confidence: 0.6 }],
  round: [{ axis: "tannin", value: 2.5, confidence: 0.45 }],
  abrasive: [{ axis: "bitterness_phenolic_grip", value: 4.5, confidence: 0.75 }],

  // Sweetness perception
  dry: [{ axis: "sweetness_perception", value: 1, confidence: 0.8 }],
  "off dry": [{ axis: "sweetness_perception", value: 2.5, confidence: 0.85 }],
  "semi sweet": [{ axis: "sweetness_perception", value: 3.5, confidence: 0.85 }],
  sweet: [{ axis: "sweetness_perception", value: 4.5, confidence: 0.8 }],
  luscious: [{ axis: "sweetness_perception", value: 4, confidence: 0.6 }],
  honeyed: [{ axis: "sweetness_perception", value: 4, confidence: 0.7 }],
  candied: [{ axis: "sweetness_perception", value: 4.5, confidence: 0.65 }],
  confected: [{ axis: "sweetness_perception", value: 4.2, confidence: 0.6 }],
  "residual sugar": [{ axis: "sweetness_perception", value: 3, confidence: 0.7 }],
  brut: [{ axis: "sweetness_perception", value: 1, confidence: 0.8 }],

  // Oak / fermentation / toast
  oaky: [{ axis: "oak_presence", value: 4.5, confidence: 0.95 }],
  "lots of oak": [{ axis: "oak_presence", value: 5, confidence: 0.95 }],
  "new oak": [{ axis: "oak_presence", value: 4.5, confidence: 0.75 }],
  "french oak": [{ axis: "oak_presence", value: 3.8, confidence: 0.65 }],
  "american oak": [{ axis: "oak_presence", value: 4.2, confidence: 0.65 }],
  oak: [{ axis: "oak_presence", value: 3.2, confidence: 0.4 }],
  vanilla: [{ axis: "oak_presence", value: 3.6, confidence: 0.6 }],
  "vanilla bean": [{ axis: "oak_presence", value: 3.8, confidence: 0.65 }],
  toast: [{ axis: "oak_presence", value: 3.8, confidence: 0.65 }],
  toasty: [{ axis: "oak_presence", value: 4, confidence: 0.75 }],
  cedar: [{ axis: "oak_presence", value: 3.5, confidence: 0.6 }],
  smoke: [{ axis: "oak_presence", value: 3.5, confidence: 0.45 }],
  smoky: [{ axis: "oak_presence", value: 3.5, confidence: 0.5 }],
  charred: [{ axis: "oak_presence", value: 4, confidence: 0.6 }],
  caramel: [{ axis: "oak_presence", value: 3.5, confidence: 0.5 }],
  butterscotch: [{ axis: "oak_presence", value: 3.5, confidence: 0.5 }],
  coconut: [{ axis: "oak_presence", value: 3.5, confidence: 0.55 }],
  brioche: [{ axis: "oak_presence", value: 3.2, confidence: 0.5 }],
  coffee: [{ axis: "oak_presence", value: 3.5, confidence: 0.45 }],
  mocha: [{ axis: "oak_presence", value: 3.5, confidence: 0.45 }],
  espresso: [{ axis: "oak_presence", value: 3.6, confidence: 0.45 }],
  cocoa: [{ axis: "oak_presence", value: 3.3, confidence: 0.45 }],
  barrel: [{ axis: "oak_presence", value: 3.8, confidence: 0.5 }],
  "wood spice": [{ axis: "oak_presence", value: 3.8, confidence: 0.6 }],
  buttery: [{ axis: "oak_presence", value: 3, confidence: 0.5 }],

  // Fruit ripeness
  green: [{ axis: "fruit_ripeness", value: 1.5, confidence: 0.65 }],
  unripe: [{ axis: "fruit_ripeness", value: 1, confidence: 0.9 }],
  underripe: [{ axis: "fruit_ripeness", value: 1.25, confidence: 0.9 }],
  ripe: [{ axis: "fruit_ripeness", value: 4, confidence: 0.7 }],
  "ripe fruit": [{ axis: "fruit_ripeness", value: 4.5, confidence: 0.8 }],
  jammy: [{ axis: "fruit_ripeness", value: 5, confidence: 0.85 }],
  overripe: [{ axis: "fruit_ripeness", value: 5, confidence: 0.9 }],
  "baked fruit": [{ axis: "fruit_ripeness", value: 4.8, confidence: 0.75 }],
  "stewed fruit": [{ axis: "fruit_ripeness", value: 4.8, confidence: 0.75 }],
  "dried fruit": [{ axis: "fruit_ripeness", value: 3.5, confidence: 0.6 }],
  "dark fruit": [{ axis: "fruit_ripeness", value: 4.2, confidence: 0.65 }],
  "black fruit": [{ axis: "fruit_ripeness", value: 4.2, confidence: 0.65 }],
  "red fruit": [{ axis: "fruit_ripeness", value: 3, confidence: 0.45 }],
  tropical: [{ axis: "fruit_ripeness", value: 4, confidence: 0.55 }],
  citrus: [{ axis: "fruit_ripeness", value: 2.5, confidence: 0.45 }],
  "stone fruit": [{ axis: "fruit_ripeness", value: 3.5, confidence: 0.55 }],
  orchard: [{ axis: "fruit_ripeness", value: 3, confidence: 0.4 }],
  juicy: [{ axis: "fruit_ripeness", value: 3.8, confidence: 0.55 }],
  pruney: [{ axis: "fruit_ripeness", value: 5, confidence: 0.8 }],

  // Alcohol
  hot: [{ axis: "alcohol_perception", value: 5, confidence: 0.75 }],
  boozy: [{ axis: "alcohol_perception", value: 5, confidence: 0.85 }],
  warming: [{ axis: "alcohol_perception", value: 4, confidence: 0.65 }],
  "low alcohol": [{ axis: "alcohol_perception", value: 1.5, confidence: 0.85 }],
  "high alcohol": [{ axis: "alcohol_perception", value: 5, confidence: 0.85 }],
  warm: [{ axis: "alcohol_perception", value: 4, confidence: 0.45 }],
  heated: [{ axis: "alcohol_perception", value: 4.5, confidence: 0.45 }],

  // Earth / mineral / savory
  earthy: [{ axis: "earthy", value: 4, confidence: 0.85 }],
  "forest floor": [{ axis: "earthy", value: 4.5, confidence: 0.85 }],
  mushroom: [{ axis: "earthy", value: 4, confidence: 0.75 }],
  truffle: [{ axis: "earthy", value: 4.5, confidence: 0.75 }],
  soil: [{ axis: "earthy", value: 3.5, confidence: 0.5 }],
  loamy: [{ axis: "earthy", value: 3.8, confidence: 0.6 }],
  underbrush: [{ axis: "earthy", value: 4, confidence: 0.7 }],
  "wet leaves": [{ axis: "earthy", value: 3.8, confidence: 0.6 }],
  "tea leaf": [{ axis: "earthy", value: 3.5, confidence: 0.6 }],
  garrigue: [{ axis: "earthy", value: 4, confidence: 0.7 }],
  graphite: [{ axis: "mineral", value: 4.2, confidence: 0.8 }],
  mineral: [{ axis: "mineral", value: 4, confidence: 0.85 }],
  minerally: [{ axis: "mineral", value: 4, confidence: 0.85 }],
  chalk: [{ axis: "mineral", value: 3.5, confidence: 0.6 }],
  chalky: [{ axis: "mineral", value: 3.8, confidence: 0.65 }],
  flint: [{ axis: "mineral", value: 4.5, confidence: 0.75 }],
  flinty: [{ axis: "mineral", value: 4.5, confidence: 0.75 }],
  stony: [{ axis: "mineral", value: 4.2, confidence: 0.7 }],
  slate: [{ axis: "mineral", value: 4, confidence: 0.7 }],
  gravel: [{ axis: "mineral", value: 4, confidence: 0.65 }],
  gravelly: [{ axis: "mineral", value: 4, confidence: 0.65 }],
  "wet stone": [{ axis: "mineral", value: 4.2, confidence: 0.75 }],
  saline: [{ axis: "mineral", value: 4.2, confidence: 0.7 }],
  petrol: [{ axis: "mineral", value: 4, confidence: 0.65 }],
  "struck match": [{ axis: "mineral", value: 4.2, confidence: 0.65 }],
  savory: [{ axis: "savory", value: 4, confidence: 0.8 }],
  umami: [{ axis: "savory", value: 4.5, confidence: 0.8 }],
  meaty: [{ axis: "savory", value: 4, confidence: 0.7 }],
  gamey: [{ axis: "savory", value: 4, confidence: 0.7 }],
  leather: [{ axis: "savory", value: 3.5, confidence: 0.65 }],
  tobacco: [{ axis: "savory", value: 3.5, confidence: 0.65 }],
  olive: [{ axis: "savory", value: 3.2, confidence: 0.5 }],
  soy: [{ axis: "savory", value: 3.8, confidence: 0.55 }],
  miso: [{ axis: "savory", value: 3.8, confidence: 0.55 }],
  broth: [{ axis: "savory", value: 3.5, confidence: 0.5 }],
  bacon: [{ axis: "savory", value: 3.8, confidence: 0.55 }],
  bay: [{ axis: "savory", value: 3, confidence: 0.4 }],
  herbal: [{ axis: "savory", value: 3, confidence: 0.5 }],
  herb: [{ axis: "savory", value: 3, confidence: 0.5 }],
  herbs: [{ axis: "savory", value: 3, confidence: 0.5 }],
  pepper: [{ axis: "savory", value: 3.2, confidence: 0.45 }],
  spice: [{ axis: "savory", value: 3, confidence: 0.4 }],
  spicy: [{ axis: "savory", value: 3, confidence: 0.4 }],
  clove: [{ axis: "savory", value: 3.2, confidence: 0.45 }],
  anise: [{ axis: "savory", value: 3.2, confidence: 0.45 }],
  licorice: [{ axis: "savory", value: 3.2, confidence: 0.45 }],
  mint: [{ axis: "savory", value: 2.8, confidence: 0.4 }],
  eucalyptus: [{ axis: "savory", value: 3, confidence: 0.45 }],
  tea: [{ axis: "savory", value: 2.8, confidence: 0.35 }],

  // Complexity / finish / aromatic intensity
  complex: [{ axis: "complexity", value: 4.5, confidence: 0.8 }],
  layered: [{ axis: "complexity", value: 4.5, confidence: 0.7 }],
  nuanced: [{ axis: "complexity", value: 4.5, confidence: 0.7 }],
  intricate: [{ axis: "complexity", value: 4.5, confidence: 0.7 }],
  simple: [{ axis: "complexity", value: 1.5, confidence: 0.7 }],
  "one dimensional": [{ axis: "complexity", value: 1, confidence: 0.85 }],
  "long finish": [{ axis: "finish_length", value: 5, confidence: 0.9 }],
  lingering: [{ axis: "finish_length", value: 4.5, confidence: 0.75 }],
  persistent: [{ axis: "finish_length", value: 4.5, confidence: 0.7 }],
  "short finish": [{ axis: "finish_length", value: 1.5, confidence: 0.9 }],
  "fades quickly": [{ axis: "finish_length", value: 1.5, confidence: 0.8 }],
  finish: [{ axis: "finish_length", value: 3, confidence: 0.2 }],
  aromatic: [{ axis: "aromatic_intensity", value: 4, confidence: 0.7 }],
  fragrant: [{ axis: "aromatic_intensity", value: 4.5, confidence: 0.75 }],
  perfumed: [{ axis: "aromatic_intensity", value: 4.5, confidence: 0.75 }],
  expressive: [{ axis: "aromatic_intensity", value: 4, confidence: 0.65 }],
  lifted: [{ axis: "aromatic_intensity", value: 4, confidence: 0.55 }],
  muted: [{ axis: "aromatic_intensity", value: 1.5, confidence: 0.7 }],
  closed: [{ axis: "aromatic_intensity", value: 1.5, confidence: 0.65 }],
  subdued: [{ axis: "aromatic_intensity", value: 2, confidence: 0.55 }],
  intense: [
    { axis: "aromatic_intensity", value: 4.5, confidence: 0.65 },
    { axis: "concentration", value: 4, confidence: 0.45 },
  ],
  concentrated: [{ axis: "concentration", value: 4.5, confidence: 0.85 }],
  focused: [{ axis: "concentration", value: 4, confidence: 0.5 }],
  packed: [{ axis: "concentration", value: 4.5, confidence: 0.75 }],
  diluted: [{ axis: "concentration", value: 1.5, confidence: 0.8 }],
  dilute: [{ axis: "concentration", value: 1.5, confidence: 0.8 }],
  watery: [{ axis: "concentration", value: 1, confidence: 0.85 }],
};

export const AROMA_CLUSTERS: Record<string, string[]> = {
  dark_fruit: [
    "dark fruit",
    "black fruit",
    "blackberry",
    "black cherry",
    "blackcurrant",
    "cassis",
    "plum",
    "blueberry",
    "bramble",
  ],
  red_fruit: [
    "red fruit",
    "red berry",
    "red cherry",
    "cherry",
    "raspberry",
    "strawberry",
    "cranberry",
    "sour cherry",
  ],
  tropical_fruit: ["tropical", "tropical fruit", "pineapple", "mango", "passion fruit", "lychee", "guava"],
  citrus: ["citrus", "citrus peel", "lemon", "lime", "grapefruit", "orange", "tangerine", "zest"],
  stone_fruit: ["stone fruit", "peach", "apricot", "nectarine"],
  floral: ["floral", "rose", "violet", "lavender", "jasmine", "blossom", "peony"],
  spice: ["spice", "spicy", "pepper", "black pepper", "white pepper", "cinnamon", "clove", "anise", "licorice", "nutmeg"],
  earth: ["earth", "earthy", "forest floor", "mushroom", "truffle", "soil", "loamy", "underbrush", "wet leaves"],
  oak_vanilla: [
    "oak",
    "oaky",
    "vanilla",
    "vanilla bean",
    "toast",
    "toasty",
    "cedar",
    "smoke",
    "smoky",
    "charred",
    "caramel",
    "butterscotch",
    "coconut",
    "brioche",
    "coffee",
    "mocha",
    "espresso",
    "cocoa",
    "wood spice",
    "barrel",
  ],
  herbal: ["herb", "herbal", "thyme", "rosemary", "sage", "mint", "eucalyptus", "grass", "grassy", "nettle", "tea", "tea leaf", "bay leaf"],
  mineral: ["mineral", "minerally", "chalk", "chalky", "flint", "flinty", "slate", "stone", "wet stone", "gravel", "gravelly", "saline", "graphite", "petrol", "struck match"],
  savory: ["leather", "tobacco", "meat", "meaty", "umami", "olive", "soy", "miso", "gamey", "broth", "bacon"],
};

export const POSITIVE_SENTIMENT = [
  "excellent",
  "amazing",
  "wonderful",
  "beautiful",
  "outstanding",
  "incredible",
  "fantastic",
  "perfect",
  "love",
  "loved",
  "lovely",
  "stunning",
  "delicious",
  "gorgeous",
  "brilliant",
  "exceptional",
  "impressive",
  "superb",
  "magnificent",
  "sublime",
  "great",
  "really good",
  "very good",
  "enjoy",
  "enjoyed",
  "favorite",
  "favourite",
  "wow",
  "refined",
  "polished",
  "sophisticated",
  "elegant",
  "graceful",
  "seamless",
  "energetic",
  "classic",
  "world class",
];

export const NEGATIVE_SENTIMENT = [
  "awful",
  "terrible",
  "horrible",
  "disgusting",
  "undrinkable",
  "disappointing",
  "disappointed",
  "mediocre",
  "bland",
  "boring",
  "corked",
  "oxidized",
  "vinegar",
  "bad",
  "worst",
  "dislike",
  "unpleasant",
  "harsh",
  "rough",
  "not good",
  "didnt like",
  "wouldnt buy",
  "waste",
  "regret",
  "dull",
  "tired",
  "muddy",
  "aggressive",
  "over oaked",
  "woody",
  "flawed",
];
