import { NextResponse } from "next/server";
import { createSupabaseServerClient } from "@/lib/supabase/server";

type WineNotificationRow = {
  id: string;
  entry_id: string;
};

function isMissingSharedTastingColumns(message: string) {
  return (
    message.includes("root_entry_id") ||
    message.includes("is_feed_visible") ||
    message.includes("column") ||
    message.includes("schema")
  );
}

async function findSuppressedTagNotificationIds({
  supabase,
  viewerUserId,
  notifications,
}: {
  supabase: Awaited<ReturnType<typeof createSupabaseServerClient>>;
  viewerUserId: string;
  notifications: WineNotificationRow[];
}) {
  const suppressedIds = new Set<string>();
  const entryIds = Array.from(
    new Set((notifications ?? []).map((row) => row.entry_id))
  );

  if (entryIds.length === 0) {
    return suppressedIds;
  }

  // Suppress tag notifications that were generated by users creating shared-tasting
  // copies of one of the viewer's own canonical entries.
  const { data: entryRows, error: entryError } = await supabase
    .from("wine_entries")
    .select("id, root_entry_id")
    .in("id", entryIds);

  if (entryError) {
    if (isMissingSharedTastingColumns(entryError.message ?? "")) {
      return suppressedIds;
    }
    return suppressedIds;
  }

  const entryRootMap = new Map(
    (entryRows ?? []).map((row) => [
      row.id as string,
      typeof (row as { root_entry_id?: unknown }).root_entry_id === "string"
        ? ((row as { root_entry_id: string }).root_entry_id as string)
        : null,
    ])
  );

  const rootIds = Array.from(
    new Set(
      (entryRows ?? [])
        .map((row) =>
          typeof (row as { root_entry_id?: unknown }).root_entry_id === "string"
            ? ((row as { root_entry_id: string }).root_entry_id as string)
            : null
        )
        .filter((id): id is string => Boolean(id))
    )
  );

  if (rootIds.length === 0) {
    return suppressedIds;
  }

  const { data: rootRows, error: rootError } = await supabase
    .from("wine_entries")
    .select("id, user_id")
    .in("id", rootIds);

  if (rootError) {
    return suppressedIds;
  }

  const rootUserMap = new Map(
    (rootRows ?? []).map((row) => [
      row.id as string,
      (row as { user_id: string }).user_id,
    ])
  );

  (notifications ?? []).forEach((notification) => {
    const rootId = entryRootMap.get(notification.entry_id);
    if (!rootId) return;
    if (rootUserMap.get(rootId) === viewerUserId) {
      suppressedIds.add(notification.id);
    }
  });

  return suppressedIds;
}

export async function GET(request: Request) {
  const supabase = await createSupabaseServerClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const url = new URL(request.url);
  const countOnly = url.searchParams.get("count_only") === "true";

  const { data: rawTagRows, error: rawTagError } = await supabase
    .from("wine_notifications")
    .select("id, entry_id")
    .eq("user_id", user.id)
    .is("seen_at", null);

  if (rawTagError) {
    return NextResponse.json({ error: rawTagError.message }, { status: 500 });
  }

  const suppressedTagNotificationIds = await findSuppressedTagNotificationIds({
    supabase,
    viewerUserId: user.id,
    notifications: (rawTagRows ?? []) as WineNotificationRow[],
  });

  const effectiveTagCount = Math.max(
    0,
    (rawTagRows ?? []).length - suppressedTagNotificationIds.size
  );

  const { count: requestCount } = await supabase
    .from("friend_requests")
    .select("id", { count: "exact", head: true })
    .eq("recipient_id", user.id)
    .eq("status", "pending")
    .is("seen_at", null);

  // Fast path: only return the count (used by AlertsMenu badge on mount)
  if (countOnly) {
    return NextResponse.json({
      unseen_count: effectiveTagCount + (requestCount ?? 0),
    });
  }

  const { data: notifications, error } = await supabase
    .from("wine_notifications")
    .select("id, entry_id, actor_id, created_at, seen_at")
    .eq("user_id", user.id)
    .is("seen_at", null)
    .order("created_at", { ascending: false })
    .limit(10);

  if (error) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }

  const filteredNotifications = (notifications ?? []).filter(
    (row) => !suppressedTagNotificationIds.has(row.id)
  );

  const { data: friendRequests } = await supabase
    .from("friend_requests")
    .select("id, requester_id, created_at, seen_at, status")
    .eq("recipient_id", user.id)
    .eq("status", "pending")
    .is("seen_at", null)
    .order("created_at", { ascending: false })
    .limit(10);

  const entryIds = Array.from(
    new Set(filteredNotifications.map((n) => n.entry_id))
  );
  const actorIds = Array.from(
    new Set(filteredNotifications.map((n) => n.actor_id))
  );
  const requesterIds = Array.from(
    new Set((friendRequests ?? []).map((request) => request.requester_id))
  );

  const { data: entries } =
    entryIds.length > 0
      ? await supabase
          .from("wine_entries")
          .select("id, wine_name, consumed_at")
          .in("id", entryIds)
      : { data: [] };

  const { data: actors } =
    actorIds.length > 0
      ? await supabase
          .from("profiles")
          .select("id, display_name, email")
          .in("id", actorIds)
      : { data: [] };

  const { data: requesters } =
    requesterIds.length > 0
      ? await supabase
          .from("profiles")
          .select("id, display_name, email")
          .in("id", requesterIds)
      : { data: [] };

  const entryMap = new Map(
    (entries ?? []).map((entry) => [entry.id, entry])
  );
  const actorMap = new Map(
    (actors ?? []).map((actor) => [
      actor.id,
      actor.display_name ?? actor.email ?? "Unknown",
    ])
  );
  const requesterMap = new Map(
    (requesters ?? []).map((requester) => [
      requester.id,
      requester.display_name ?? requester.email ?? "Unknown",
    ])
  );

  const tagItems = filteredNotifications.map((n) => ({
    id: n.id,
    type: "tagged" as const,
    entry_id: n.entry_id,
    actor_name: actorMap.get(n.actor_id) ?? "Unknown",
    wine_name: entryMap.get(n.entry_id)?.wine_name ?? null,
    consumed_at: entryMap.get(n.entry_id)?.consumed_at ?? "",
    created_at: n.created_at,
  }));

  const requestItems = (friendRequests ?? []).map((request) => ({
    id: request.id,
    type: "friend_request" as const,
    requester_id: request.requester_id,
    requester_name: requesterMap.get(request.requester_id) ?? "Unknown",
    created_at: request.created_at,
  }));

  const result = [...tagItems, ...requestItems].sort((a, b) =>
    b.created_at.localeCompare(a.created_at)
  );

  return NextResponse.json({
    unseen_count: effectiveTagCount + (requestCount ?? 0),
    notifications: result,
  });
}
